# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RedditFeedDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RedditFeedDemo
  pod 'Alamofire', '~> 5.0.0-rc.3'

  target 'RedditFeedDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RedditFeedDemoUITests' do
    # Pods for testing
  end

end
